---
## handlers
- name: start_mariadb
  systemd:
    name: mariadb.service
    state: started
    enabled: yes
  become: yes
  listen: "start_mariadb"

- name: restart_mariadb
  systemd:
    name: mariadb.service
    state: restarted
  become: yes
  listen: "restart_mariadb"
