---
# Configure zabbix server setting
- name: Change timezone for php.ini
  lineinfile:
    path: /etc/php-fpm.d/zabbix.conf
    regex: "^php_value[date.timezone] = Asia/Tokyo"
    insertafter: "^; php_value[date.timezone] = Europe/Riga"
    line: "php_value[date.timezone] = Asia/Tokyo"
    firstmatch: true

- name: Set Zabbix Server config file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: "0600"

- name: Restart service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm

- name: Wait for Zabbix Server Service
  wait_for:
    host: "{{ ansible_host }}"
    port: 80
    delay: 10
    state: started

- debug:
    msg: Access to http://{{ ansible_host }}/zabbix/
# - debug:
#     msg: 'file id {{item.item.path}} (name {{item.item.logname}}) exists'
#   with_items: "{{ log_file.results }}"
#   when: item.stat.exists
