---
- name: Zabbix-server install check
  dnf:
    list: zabbix-server
  register: dnf_check_server

- name: Install zabbix repository
  dnf:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: latest

- name: Install zabbix server, frontend, agent
  dnf:
    name: "{{ zabbix_packages }}"
  vars:
    zabbix_packages:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-apache-conf
    - zabbix-agent
    state: latest
