---
# Stop Selinux and Disable auto run
- name: configure / Selinux off and disable
  selinux:
    #policy: targeted
    state: disabled

# Disable ipv6 interface
- name: configure / Disable ipv6 interface
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_file: /etc/sysctl.d/20-network.conf
    sysctl_set: yes
    reload: yes
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

# Update all packages installed
- name: configure / update dnf packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

# Add epel repository
- name: configure / import EPEL Repository
  dnf:
    name: epel-release
    state: latest
    update_cache: yes
