---
# Import Initial Database schema
- name: configure / Check zabbix table existence
  shell: mysql "-u{{ mariadb.root }}" "-p{{ mariadb.root_password }}" "{{ mariadb.db_name }}" -e 'show tables;' | wc -l
  include_vars: ../mariadb/vars/main.yml
  register: zabbix_table_count

- name: configure / Import initial schema and data
  shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 "-u{{ mariadb.user }}" "-p{{ mariadb.user_password }}" "{{ mariadb.db_name }}"
  include_vars: ../mariadb/vars/main.yml
  when: zabbix_table_count.stdout == "0"

# Configure zabbix server setting
- name: configure / change timezone for php.ini
  lineinfile:
    path: "{{ php_fpm.conf_dir }}{{ php_fpm.conf }}"
    regex: "{{ php_fpm.regex }}"
    insertafter: "{{ php_fpm.insertafter }}"
    line: "{{ php_fpm.line }}"
    #firstmatch: true

- name: configure / set Zabbix Server config file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: "0600"

- name: configure / Restart service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop: "{{ zabbix.service }}"

- name: configure / Wait for Zabbix Server Service
  wait_for:
    host: "{{ ansible_host }}"
    port: 80
    delay: 5
    connect_timeout: 2
    timeout: 300
    state: started

- debug:
    msg: Access to zabbix http://{{ ansible_host }}/zabbix/
