# Note: Zabbix 6.0 needs Mariadb 10.5.x to 10.6.x, 10.7.x is not supported 2022.2.20 now.
- name: Download Mariadb Repository script
  get_url:
    url: https://r.mariadb.com/downloads/mariadb_repo_setup
    dest: /tmp/

- name: Install MariaDB Repository
  shell: bash /tmp/mariadb_repo_setup --mariadb-server-version=10.6
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_version | float >= 20.04

- name: Install Database Server for RHEL distribution
  dnf:
    name: "{{ database_packages }}"
    update_cache: yes
    enablerepo: mariadb
    state: latest
  vars:
    database_packages:
      - MariaDB-client
      - MariaDB-server
      - MariaDB-common
      - python3-PyMySQL
  when:
    - ansible_distribution in ["CentOS", "AlmaLinux", "RedHat"]
    - ansible_distribution_major_version == "8"

- name: Install Database Server for Debian distribution
  apt:
    name: "{{ database_packages }}"
    update_cache: yes
    state: latest
  vars:
    database_packages:
      - mariadb-client-10.6
      - mariadb-server-10.6
      - mariadb-common
      - python3-pymysql
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_version | float >= 20.04
