---
## handlers
- name: start_zabbix_server
  systemd:
    name: zabbix-server.service
    state: started
    enabled: yes
  become: yes
  listen: "start_zabbix_server"

- name: restart_zabbix_server
  systemd:
    name: zabbix-server.service
    state: restarted
  become: yes
  listen: "restart_zabbix_server"
