---
- name: install / chronyd
  dnf:
    name: chrony
    state: latest
    update_cache: yes
  when:
    - ansible_distribution in ["CentOS", "AlmaLinux", "RedHat", "Rocky"]
    - ansible_distribution_major_version == "8"

- name: install / chronyd
  apt:
    name: chrony
    state: latest
    update_cache: yes
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_version | float >= 20.04
