---
# Time settings
- name: configure / timezone
  timezone:
    name: Asia/Tokyo

- name: configure / set chrony.conf
  template:
    src: "{{ chrony.conf_src }}"
    dest: "{{ chrony.conf_dir }}{{ chrony.conf }}"
    owner: root
    group: root
    mode: 0644

- name: configure / restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: configure / sync system time
  command: chronyc sources
  register: time_sync_result
  ignore_errors: yes

- debug:
    msg: "{{ time_sync_result.stdout }}"
