---
# vars:
# ansible_sudo_pass: 'ansible'

# environment:
# http_proxy: "http://proxy.jp:8080"
# https_proxy: "http://proxy.jp:8080"

- name: Deploy zabbix server
  hosts: maria_db
  become: true
  order: inventory
  roles:
    - { role: common, tags: common }
    - { role: mariadb, tags: mariadb }

- name: Deploy zabbix server
  hosts: zabbix_server
  become: true
  roles:
    - { role: zabbix, tags: zabbix }

      #  post_tasks:
      #    - name: Restart target nodes
      #      reboot:
      #        reboot_timeout: 300
      #
      #    - name: Waiting for servers to come back
      #      wait_for:
      #        host: "{{ inventory_hostname }}"
      #        port: 22
      #        state: started
      #        delay: 30
      #        timeout: 300
      #      delegate_to: 127.0.0.1
